export const shell = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Content Desk · 内容工作台</title><style>/*DESK_STYLE*/</style></head><body>
<header class="topbar"><div class="brand"><span class="brand-mark">C.</span><div><b>Content Desk</b> <a href="/studio" style="color:var(--teal);font-size:12px">模块与生成 ↗</a></div></div><div id="save-state" hidden>正在读取文章…</div><div id="notice" role="status">正在读取文章…</div><button id="settings-menu" class="quiet">设置</button></header>
<section class="series-overview" aria-label="系列与推文" id="series-overview">
<div class="overview-heading"><h2>推文系列</h2><button id="overview-toggle" class="quiet" aria-expanded="true" aria-controls="series-picker">收起 ∧</button></div>
<div id="series-picker" class="series-picker"><div id="series-tabs" class="series-tabs" role="group" aria-label="切换推文系列"></div><select id="series" aria-label="推文系列" hidden></select><button id="add-series" class="quiet">＋ 添加系列</button></div>
<div id="overview-context" class="overview-context" hidden></div>
<div id="overview-body"><div class="overview-tools"><span id="library-count"></span><div class="filters" role="group" aria-label="文章筛选"><button data-filter="all" aria-pressed="true">全部</button><button data-filter="pending" aria-pressed="false">待检查</button><button data-filter="synced" aria-pressed="false">已同步</button></div><input id="search" type="search" aria-label="搜索文章" placeholder="搜索本系列推文"><button id="new" class="small">＋ 新一期</button><button id="import" class="quiet" hidden>导入</button><button id="logs" class="quiet" hidden>自动化记录</button></div>
<div class="series-contents"><button id="template" class="template-card"><span class="template-icon" aria-hidden="true">▤</span><span><small>系列模板 · 可复用</small><b id="template-series-name">排版规范</b><span class="template-structure" aria-hidden="true"><i></i><i></i><i></i></span><em>编辑模板 ↗</em></span></button><div id="issues" class="issues" aria-label="本系列正式推文"></div></div></div></section>
<main class="workspace">
<section class="editor-column"><div class="article-controls"><div class="article-heading"><div><span class="eyebrow" id="article-kicker" hidden>本地文章</span><h1 id="article-heading">选择一篇文章开始</h1></div><div class="row article-actions"><button id="save">保存版本</button><button id="sync" class="primary" disabled>检查并同步</button><select id="review" aria-label="人工审查"><option value="pending">待检查</option><option value="reviewed">本版本已检查</option><option value="published">已发布（人工记录）</option></select><button id="history" class="quiet">历史版本</button><button id="export" class="quiet" hidden>导出备份</button></div></div>
<div class="format-toolbar" role="toolbar" aria-label="正文编辑工具"><button data-command="undo" title="撤销">↶</button><button data-command="redo" title="重做">↷</button><span class="divider"></span><button data-block="p">正文</button><button data-block="h2">小标题</button><button data-command="bold"><b>B</b></button><button data-command="italic"><i>I</i></button><button data-command="hilite">重点</button><button data-command="insertUnorderedList">列表</button><button data-block="blockquote">引用</button><button id="link">链接</button><button data-command="removeFormat">清格式</button><button id="insert-image">＋ 图片</button></div>
<div class="canvas-toolbar"><div class="row"><button data-width="390" aria-pressed="true">手机</button><button data-width="680" aria-pressed="false">宽屏</button></div><span id="word-count">—</span><button id="copy" class="quiet">复制公众号全文</button></div>
<nav id="module-nav" class="module-nav" aria-label="文章模块定位"></nav></div><div id="canvas" class="canvas"><div id="document" aria-label="文章编辑画布"></div><div id="empty" class="empty"><h2>让每一期，都从好模板开始。</h2><p>选择文章，或导入自动化产出的图文备份。</p></div></div></section>
<aside class="inspector"><div class="inspector-sticky"><div class="pane-heading"><h2>文章设置</h2><span id="selection-label">全文</span></div><div class="follow-controls"><label class="check-label"><input id="follow-settings" type="checkbox" checked>滚动文章，自动跟随设置</label><span id="follow-state" aria-live="polite">自动跟随已开启</span></div></div><section id="image-tools" hidden><h3>选中图片</h3><img id="image-preview" alt="选中图片预览"><label>图片说明<input id="image-alt" maxlength="200"></label><label>图注<input id="image-caption" maxlength="300"></label><label>来源链接<input id="image-source" type="url" placeholder="https://…"></label><label>图片宽度 <output id="image-width-value">100%</output><input id="image-width" type="range" min="30" max="100" value="100"></label><label>图片对齐<select id="image-align"><option value="center">居中</option><option value="left">左对齐</option><option value="right">右对齐</option></select></label><div class="row"><button id="image-replace">替换</button><button id="image-up">上移</button><button id="image-down">下移</button><button id="image-remove">移除</button></div><label>裁切比例<select id="crop-ratio"><option value="1.7777778">横图 16:9</option><option value="1">方图 1:1</option><option value="2.35">封面 2.35:1</option><option value="0.75">竖图 3:4</option></select></label><button id="crop" class="wide">居中裁切为实际图片</button><small>裁切后可撤销；官方截图优先保留完整信息。</small></section>
<details data-settings-section="title"><summary>标题与摘要</summary><label>文章标题<input id="title" maxlength="64"></label><label>摘要<textarea id="digest" maxlength="120" placeholder="用于公众号消息摘要，最多 120 字"></textarea></label><p id="receipt" class="muted">尚未同步</p></details>
<details data-settings-section="layout"><summary>开头 · 布局组合</summary><label>开头顺序<select id="block-order" data-setting><option value="logo,cover,caption">Logo → 封面 → 标语</option><option value="cover,logo,caption">封面 → Logo → 标语</option><option value="logo,caption,cover">Logo → 标语 → 封面</option></select></label><label>开头块间距<input id="cover-gap" data-setting type="number" min="0" max="48"></label></details>
<details data-settings-section="logo"><summary>开头 · Logo</summary><button id="logo-replace" class="wide">替换品牌 Logo</button><small>品牌字标独立于本期封面。</small></details>
<details data-settings-section="cover"><summary>开头 · 本期封面</summary><img id="cover-preview" class="cover-preview" alt="本期封面"><button id="cover-replace" class="wide">替换本期封面</button><small>上图为消息缩略图裁切预览；正文保留完整封面。</small></details>
<details data-settings-section="caption"><summary>开头 · 主题标语</summary><label>主题标语<textarea id="caption" data-setting maxlength="200"></textarea></label><label>标语字号<input id="caption-size" data-setting type="number" min="12" max="28"></label></details>
<details data-settings-section="body"><summary>正文 · 排版</summary><label>文章底色<select id="theme" data-setting><option value="deep">石墨黑</option><option value="nebula">午夜蓝</option><option value="eclipse">曜石黑</option><option value="stardust">静谧墨青</option><option value="none">透明 · 跟随读者端</option><option value="solid">自选颜色</option></select></label><label>自选底色<input id="solid-color" data-setting type="color" value="#101113"></label><label>品牌强调色<select id="accent" data-setting><option value="yellow">暖黄</option><option value="teal">薄荷青</option></select></label><div class="row"><label>正文字号<input id="body-size" data-setting type="number" min="14" max="22" value="16"></label><label>行距<input id="body-line" data-setting type="number" min="1.4" max="2.5" step="0.05" value="1.9"></label></div><div class="row"><label>段间距<input id="body-gap" data-setting type="number" min="8" max="36" value="18"></label><label>左右留白<input id="body-padding" data-setting type="number" min="12" max="36" value="20"></label></div><button id="apply-template" class="wide">应用系列模板到本文</button></details>
<details data-settings-section="sources"><summary>文末 · 事实依据</summary><label>事实依据<textarea id="sources" placeholder="列出来源、日期和待核实项"></textarea></label></details><details data-settings-section="signature"><summary>文末 · 品牌签名</summary><label class="check-label"><input type="checkbox" id="signature-enabled" data-setting>显示文末签名</label><label>签名文字<input id="signature-text" data-setting maxlength="100"></label></details><details data-settings-section="export" hidden><summary>全文 · 检查与同步</summary><div id="checks"></div><p id="connection" class="muted">正在检查连接…</p><button id="reconnect" class="wide">重新检查公众号连接</button></details></aside></main>
<dialog id="dialog"><div class="dialog-head"><h2 id="dialog-title"></h2><button id="dialog-close" aria-label="关闭对话框">×</button></div><div id="dialog-content"></div></dialog><input type="file" id="file" hidden accept="image/png,image/jpeg,image/webp"><input type="file" id="import-file" hidden accept="application/json"><script>/*DESK_SCRIPT*/</script></body></html>`;
