import {defaults,templateSettings,styleRules,palette,type Settings} from './article-format';
export interface SeriesTemplate{revision:string;seriesId:string;settings:Settings;logo:string;savedAt:string;sample?:{title:string;body:string}}
const demo={title:'让新想法，成为值得分享的内容',body:'这是一份独立的模板文案。你可以在这里修改文字与排版，观察读者看到的文章效果。\n\n## 从一个清楚的问题开始\n好的文章，先让读者知道发生了什么，再解释为什么值得关注。用 **重点文字** 标记最想让读者记住的判断。\n\n> 引用示例：每一个判断，都应该有可以核对的依据。\n\n## 给读者一个可用的方法\n- 先确认事实与来源\n- 再呈现推理与不同观点\n- 最后留下一个具体的问题\n\n你想让这个系列带给读者什么？从这里开始，设计属于你的阅读节奏。'};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function editTemplate(options:{seriesId:string;name:string;existing:SeriesTemplate|null;settings:Settings;logo:string;save:(value:unknown)=>Promise<unknown>}){
 const dlg=document.createElement('dialog');dlg.className='template-editor';
 const s=templateSettings(options.existing?.settings||options.settings||defaults),sample={...(options.existing?.sample||demo)};let logo=options.existing?.logo||options.logo;
 dlg.innerHTML=`<div class="dialog-head"><h2>${escape(options.name)} · 系列模板</h2><button data-close aria-label="关闭模板编辑">×</button></div><div class="template-edit-grid"><div class="template-fields"><label>示例标题<input data-title maxlength="64"></label><label>模板文案<textarea data-body rows="10"></textarea></label><small>支持 ## 小标题、**强调**、&gt; 引用和 - 列表，仅用于模板预览。</small><div data-style-fields></div><label>品牌 Logo<input data-logo type="file" accept="image/png,image/jpeg,image/webp"></label></div><div class="template-preview-wrap"><div data-preview></div></div></div><div class="template-editor-footer"><span data-status role="status">保存后，后续新文章使用此模板。</span><button data-save class="primary">保存为最新模板</button></div>`;
 document.body.append(dlg);const q=<T extends HTMLElement>(selector:string)=>dlg.querySelector<T>(selector)!;
 q<HTMLInputElement>('[data-title]').value=sample.title;q<HTMLTextAreaElement>('[data-body]').value=sample.body;
 const fields=q('[data-style-fields]');
 const names:Record<string,string>={theme:'文章底色','solid-color':'自选底色',accent:'强调色','body-size':'正文字号','body-line':'行距','body-gap':'段间距','body-padding':'左右留白','block-order':'开头顺序',caption:'主题标语','caption-size':'标语字号','cover-gap':'开头间距','signature-enabled':'显示签名','signature-text':'签名文字'};
 const choices:Record<string,Array<[string,string]>>={theme:[['deep','石墨黑'],['nebula','午夜蓝'],['eclipse','纯黑'],['stardust','墨青'],['none','透明'],['solid','自选']],accent:[['yellow','暖黄'],['teal','薄荷青']],'block-order':[['logo,cover,caption','Logo → 封面 → 标语'],['cover,logo,caption','封面 → Logo → 标语'],['logo,caption,cover','Logo → 标语 → 封面']]};
 const ranges:Record<string,[number,number,string]>={'body-size':[14,22,'1'],'body-line':[1.4,2.5,'.1'],'body-gap':[8,36,'1'],'body-padding':[12,36,'1'],'caption-size':[12,28,'1'],'cover-gap':[0,48,'1']};
 for(const key of Object.keys(defaults)){const label=document.createElement('label');label.textContent=names[key];let input:HTMLInputElement|HTMLSelectElement;
 if(choices[key]){input=document.createElement('select');for(const [value,text] of choices[key])input.add(new Option(text,value));input.value=String(s[key]);}
 else{input=document.createElement('input');input.type=typeof s[key]==='boolean'?'checkbox':key==='solid-color'?'color':ranges[key]?'number':'text';if(input.type==='checkbox'){input.checked=Boolean(s[key]);label.className='check-label';}else input.value=String(s[key]);if(ranges[key]){input.min=String(ranges[key][0]);input.max=String(ranges[key][1]);input.step=ranges[key][2];}}
 input.dataset.templateSetting=key;input.oninput=()=>{s[key]=input instanceof HTMLInputElement&&input.type==='checkbox'?input.checked:input.value;render();};label.append(input);fields.append(label);}
 function render(){const preview=q('[data-preview]');const inline=(v:string)=>escape(v).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');
 const text=sample.body.split(/\n\s*\n/).map(block=>block.startsWith('## ')?'<h2>'+inline(block.slice(3))+'</h2>':block.startsWith('> ')?'<blockquote>'+inline(block.slice(2))+'</blockquote>':block.startsWith('- ')?'<ul>'+block.split('\n').map(line=>'<li>'+inline(line.replace(/^- /,''))+'</li>').join('')+'</ul>':'<p>'+inline(block).replace(/\n/g,'<br>')+'</p>').join('');
 preview.innerHTML='<section data-content-header="1"><section data-block="logo">'+(logo?'<img alt="品牌 Logo" src="'+escape(logo)+'">':'<p>品牌 Logo 预览</p>')+'</section><section data-block="cover"><div class="template-demo-cover">系列封面 · 示例</div></section><section data-block="caption"><p>'+escape(String(s.caption))+'</p></section></section><article><section><h1>'+escape(sample.title)+'</h1>'+text+'</section></article><section data-signature>'+escape(String(s['signature-text']))+'</section>';
 styleRules(s).forEach(([selector,style])=>preview.querySelectorAll<HTMLElement>(selector).forEach(el=>el.style.cssText=style));preview.style.background=palette(s).bg;const header=preview.querySelector('[data-content-header]')!;String(s['block-order']).split(',').forEach(key=>{const el=header.querySelector('[data-block="'+key+'"]');if(el)header.append(el);});
 const cover=preview.querySelector('[data-block="cover"]')!;const img=document.createElement('img');img.alt='系列封面';img.src='/api/series-cover?id='+encodeURIComponent(options.seriesId);img.style.cssText='display:block;width:100%;aspect-ratio:2.35;object-fit:cover';img.onload=()=>cover.replaceChildren(img);
 }
 q<HTMLInputElement>('[data-title]').oninput=e=>{sample.title=(e.target as HTMLInputElement).value;render();};q<HTMLTextAreaElement>('[data-body]').oninput=e=>{sample.body=(e.target as HTMLTextAreaElement).value;render();};
 q<HTMLInputElement>('[data-logo]').onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const status=q('[data-status]');if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>2800000){status.textContent='请选择 2.8MB 以内的 PNG、JPG 或 WebP';return;}logo=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});render();};
 q('[data-close]').onclick=()=>dlg.close();dlg.onclose=()=>dlg.remove();
 q<HTMLButtonElement>('[data-save]').onclick=async()=>{const button=q<HTMLButtonElement>('[data-save]'),status=q('[data-status]');button.disabled=true;try{if(!sample.title.trim()||!sample.body.trim())throw new Error('请填写示例标题和模板文案');if(!logo)throw new Error('请先选择品牌 Logo');await options.save({seriesId:options.seriesId,settings:s,logo,sample});status.textContent='最新模板已保存，后续新文章将沿用此排版。';}catch(e){status.textContent=e instanceof Error?e.message:String(e);}finally{button.disabled=false;}};
 render();dlg.showModal();
}
