import {editTemplate} from './template-editor';
import {installFollowSettings} from './follow-settings';
import {defaults,palette,styleRules,templateSettings,type Settings} from './article-format';
interface Receipt{status:string;stage:string;mediaId?:string;error?:string;updatedAt?:string}
interface Review{status:'pending'|'reviewed'|'published';updatedAt:string}
interface Item{revision:string;issueId:string;seriesId:string;title:string;savedAt:string;imageCount:number;receipt?:Receipt;review?:Review}
interface Snapshot extends Item{html:string;cover:string;settings:Settings;digest?:string}
interface Series{id:string;name:string;layout:string;settings?:Settings;description?:string;createdAt?:string}
interface Template{revision:string;seriesId:string;settings:Settings;logo:string;savedAt:string;sample?:{title:string;body:string}}
interface Bootstrap{token:string;snapshots:Item[];catalog:{series:Series[]};configured:boolean;configurationError?:string}
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const root=$('document'),dlg=$<HTMLDialogElement>('dialog');
const follow=installFollowSettings(root,sourceNode);
const overview=$('series-overview'),overviewToggle=$<HTMLButtonElement>('overview-toggle');
function toggleOverview(collapsed:boolean){overview.classList.toggle('is-collapsed',collapsed);$('series-picker').hidden=collapsed;$('overview-context').hidden=true;overviewToggle.setAttribute('aria-expanded',String(!collapsed));overviewToggle.textContent=collapsed?'展开 ∨':'收起 ∧';localStorage.setItem('desk-series-collapsed',String(collapsed));}
overviewToggle.onclick=()=>toggleOverview(overviewToggle.getAttribute('aria-expanded')==='true');
toggleOverview(localStorage.getItem('desk-series-collapsed')==='true');
let token='',items:Item[]=[],series:Series[]=[],current:Snapshot|null=null,activeSeries='',dirty=false,saving=false,busy=false,configured=false,online=false,checkingConnection=false,filter='all',selectedImage:HTMLImageElement|null=null,selectedBlock:HTMLElement|null=null,range:Range|null=null,epoch=0,saveTimer:ReturnType<typeof setTimeout>|undefined;
let undoStack:string[]=[],redoStack:string[]=[],checkpoint='',historyTimer:ReturnType<typeof setTimeout>|undefined;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(s:string)=>new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
let statusMessage='';
function notice(text:string,error=false){statusMessage=text;$('notice').textContent=text||$('save-state').textContent;$('notice').title=text;$('notice').classList.toggle('error',error);}
async function api<T>(url:string,value?:unknown):Promise<T>{const response=await fetch(url,{method:value===undefined?'GET':'POST',headers:value===undefined?{}:{'Content-Type':'application/json','X-Workbench-Token':token},body:value===undefined?undefined:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
function fail(e:unknown){notice(e instanceof Error?e.message:String(e),true);}
function dialog(title:string,html:string){$('dialog-title').textContent=title;$('dialog-content').innerHTML=html;if(!dlg.open)dlg.showModal();return $('dialog-content');}
$('dialog-close').onclick=()=>dlg.close();
$('settings-menu').onclick=()=>{dialog('工作台设置','<div class="settings-actions"><button data-action="import">导入文章 / 备份</button><button data-action="export">导出当前文章备份</button><button data-action="logs">自动化运行记录</button><button data-action="reconnect">检查公众号连接</button></div>');dlg.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button=>{button.disabled=button.dataset.action==='export'&&!current;button.onclick=()=>{dlg.close();$(button.dataset.action!).click();};});};
function body(){return root.querySelector<HTMLElement>('article>section');}
function settings(){return current?.settings||{...defaults};}
function sourceNode(){return root.querySelector<HTMLElement>('[data-sources]')||Array.from(root.querySelectorAll<HTMLElement>('article blockquote')).find(el=>/^(?:事实依据|公开资料|参考资料|资料来源|信息来源|参考来源|参考文献)\s*[：:]/.test(el.textContent?.trim()||''))||null;}
function serialize(){const clone=root.cloneNode(true) as HTMLElement;clone.querySelectorAll('*').forEach(el=>{['contenteditable','spellcheck','role','aria-label','class','tabindex'].forEach(a=>el.removeAttribute(a));});clone.querySelectorAll('p').forEach(p=>{if(!p.textContent?.trim()&&!p.querySelector('img'))p.remove();});return clone.innerHTML;}
function stateString(){return JSON.stringify({html:serialize(),settings:settings(),cover:current?.cover,digest:current?.digest,title:current?.title});}
function capture(){const next=stateString();if(checkpoint&&next!==checkpoint){undoStack.push(checkpoint);if(undoStack.length>30)undoStack.shift();redoStack=[];}checkpoint=next;}
function changed(){if(!current)return;statusMessage='';epoch++;dirty=true;current.review=undefined;clearTimeout(saveTimer);clearTimeout(historyTimer);historyTimer=setTimeout(capture,400);saveTimer=setTimeout(()=>void save().catch(fail),1500);updateState();runChecks();}
function markChanged(){capture();changed();}
function historyMove(redo=false){if(!current||busy)return;clearTimeout(historyTimer);capture();const from=redo?redoStack:undoStack,to=redo?undoStack:redoStack;const next=from.pop();if(!next)return;to.push(stateString());const data=JSON.parse(next);Object.assign(current,{settings:data.settings,cover:data.cover,digest:data.digest,title:data.title});root.innerHTML=data.html;checkpoint=next;selectedImage=null;selectedBlock=null;prepareEditing();populate();changed();}
function updateState(){
 $('save-state').textContent=saving?'正在保存…':dirty?'有修改 · 即将自动保存':current?'已保存 '+date(current.savedAt):'选择或导入文章';
 if(!statusMessage)$('notice').textContent=$('save-state').textContent;
 $<HTMLButtonElement>('save').disabled=!current||saving||busy;
 $<HTMLButtonElement>('sync').disabled=!current||!online||busy||saving||checkingConnection;
 $('sync').textContent=checkingConnection?'检查连接中…':busy?'同步处理中…':'检查并同步';$('sync').title=configured?'保存当前版本并同步微信草稿箱':'点击重新检查公众号配置并准备同步';
 const receipt=current?.receipt;$('receipt').textContent=dirty?'本地有修改 · 尚未同步':receipt?((receipt.status==='verified'?'已回读核对':'同步状态：'+receipt.stage)+(receipt.mediaId?' · '+receipt.mediaId:'')+(receipt.error?' · '+receipt.error:'')):'当前版本尚未同步';
 $<HTMLSelectElement>('review').disabled=!current||busy||saving;
 $<HTMLSelectElement>('review').value=dirty?'pending':current?.review?.status||'pending';
}
function latestItems(){return [...new Map(items.map(i=>[i.seriesId+':'+i.issueId,i] as const).reverse()).values()].sort((a,b)=>b.savedAt.localeCompare(a.savedAt));}
function list(){
 renderSeries();
 const query=$<HTMLInputElement>('search').value.trim().toLowerCase();let rows=latestItems().filter(i=>i.seriesId===activeSeries);
 $('library-count').textContent=rows.length+' 篇文章 · 本机保存';rows=rows.filter(i=>i.title.toLowerCase().includes(query)&&(filter==='all'||filter==='synced'&&i.receipt?.status==='verified'||filter==='pending'&&!i.review&&i.receipt?.status!=='verified'||filter==='pending'&&i.review?.status==='pending'));
 $('issues').innerHTML=rows.length?rows.map(i=>{const updated=items.some(x=>x.issueId===i.issueId&&x.seriesId===i.seriesId&&x.revision!==i.revision&&x.receipt?.status==='verified');const state=i.receipt?.status==='verified'?'已同步草稿':updated?'有修改待同步':i.review?.status==='published'?'已发布 · 人工':i.review?.status==='reviewed'?'已检查 · 待同步':'待检查';return `<button class="issue ${i.issueId===current?.issueId&&i.seriesId===current?.seriesId?'active':''}" data-revision="${i.revision}"><img src="/api/cover?revision=${i.revision}" alt=""><span><b>${esc(i.title)}</b><small class="${i.receipt?.status==='verified'?'synced':''}">${date(i.savedAt)} · ${state}</small></span></button>`;}).join(''):'<p class="muted">这里还没有符合条件的文章。</p>';
 $('issues').querySelectorAll<HTMLButtonElement>('[data-revision]').forEach(b=>b.onclick=()=>void openIssue(b.dataset.revision!).catch(fail));
}
function renderSeries(){
 $<HTMLSelectElement>('series').innerHTML=series.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');$<HTMLSelectElement>('series').value=activeSeries;
 $('series-tabs').innerHTML=series.map(s=>`<button class="series-card" data-series="${esc(s.id)}" aria-pressed="${s.id===activeSeries}" aria-label="${esc(s.name)}" title="${s.id===activeSeries?'点击展开系列介绍':'点击切换系列'}"><span class="series-art"><img src="/api/series-cover?id=${encodeURIComponent(s.id)}" alt=""><span class="series-art-fallback" hidden>系列</span></span><span class="series-copy"><b>${esc(s.name)}</b><small>${seriesDate(s)} · 共 ${latestItems().filter(i=>i.seriesId===s.id).length} 篇</small><span class="series-description">${esc(s.description||'尚未填写系列介绍')}</span></span><span class="series-card-arrow" aria-hidden="true">${s.id===activeSeries?'⌄':'›'}</span></button>`).join('');
 $('series-tabs').querySelectorAll<HTMLButtonElement>('[data-series]').forEach(button=>button.onclick=()=>{if(button.dataset.series===activeSeries){openSeriesDescription();return;}$<HTMLSelectElement>('series').value=button.dataset.series!;$('series').dispatchEvent(new Event('change'));});
 $('template-series-name').textContent=(series.find(s=>s.id===activeSeries)?.name||'系列')+' · 独立模板';
 $('series-tabs').querySelectorAll<HTMLImageElement>('.series-art img').forEach(img=>{img.onerror=()=>{img.hidden=true;(img.nextElementSibling as HTMLElement).hidden=false;};});
 $('overview-context').textContent=(series.find(s=>s.id===activeSeries)?.name||'推文系列')+'  /  '+(current?.title||'尚未选择推文');
}
function seriesDate(s:Series){const time=s.createdAt?new Date(s.createdAt):null;return time&&!Number.isNaN(time.getTime())?'创建于 '+time.toLocaleDateString('zh-CN'):'创建时间未记录';}
function openSeriesDescription(){
 const selected=series.find(s=>s.id===activeSeries);if(!selected)return;
 dialog(selected.name,`<p class="muted">${seriesDate(selected)} · 共 ${latestItems().filter(i=>i.seriesId===selected.id).length} 篇内容</p><div class="series-full-description">${esc(selected.description||'尚未填写系列介绍。')}</div><div class="dialog-actions"><button id="series-edit-description">编辑介绍</button></div>`);
 $('series-edit-description').onclick=()=>{
  dialog('编辑系列介绍',`<label>系列介绍<textarea id="series-description-input" maxlength="4000" rows="8" placeholder="介绍这个系列关注的主题、适合谁阅读，以及内容风格">${esc(selected.description||'')}</textarea></label><div class="dialog-actions"><button id="series-description-save" class="primary">保存介绍</button></div>`);
  $('series-description-save').onclick=async()=>{try{const next=series.map(s=>s.id===selected.id?{...s,description:$<HTMLTextAreaElement>('series-description-input').value.trim()}:s);await api('/api/catalog',{series:next});series=next;renderSeries();openSeriesDescription();notice('系列介绍已保存');}catch(e){fail(e);}};
 };
}
function prepareEditing(){const sources=sourceNode();if(sources)sources.dataset.sources='1';root.querySelectorAll<HTMLImageElement>('img').forEach(img=>{img.onload=runChecks;img.onerror=runChecks;});const article=body();if(article){article.contentEditable='true';article.setAttribute('role','textbox');article.setAttribute('aria-label','可编辑文章正文');article.spellcheck=false;}root.querySelectorAll<HTMLImageElement>('img').forEach(img=>{img.style.pointerEvents='auto';img.draggable=false;});$('empty').hidden=!!root.childElementCount;}
function normalizeShell(html:string){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,style,iframe,object,embed,input,button,link').forEach(n=>n.remove());doc.querySelectorAll('*').forEach(el=>{for(const attr of Array.from(el.attributes))if(attr.name.startsWith('on'))el.removeAttribute(attr.name);});const header=doc.querySelector('[data-content-header]'),article=doc.querySelector('article');if(!header||!article)throw new Error('文章缺少品牌开头或正文，请导入完整备份');const signature=doc.querySelector('[data-signature]')||article.nextElementSibling;if(signature)signature.setAttribute('data-signature','1');return header.outerHTML+article.outerHTML+(signature?.outerHTML||'<section data-signature="1"></section>');}
async function openIssue(revision:string){if(busy)throw new Error('正在同步，请完成后切换文章');if(current&&dirty)await save();if(dirty)throw new Error('请等待保存完成后再切换');const s=await api<Snapshot>('/api/snapshot?revision='+revision);clearTimeout(saveTimer);clearTimeout(historyTimer);current={...s,settings:{...defaults,...s.settings},receipt:items.find(i=>i.revision===revision)?.receipt,review:items.find(i=>i.revision===revision)?.review};activeSeries=s.seriesId;root.innerHTML=normalizeShell(s.html);selectedImage=null;selectedBlock=null;range=null;dirty=false;undoStack=[];redoStack=[];prepareEditing();populate();checkpoint=stateString();renderSeries();list();updateState();runChecks();window.scrollTo({top:0,behavior:'instant'});follow.refresh();}
function populate(){if(!current)return;$('article-heading').textContent=current.title;$('article-kicker').textContent=(series.find(s=>s.id===activeSeries)?.name||'本地文章')+' / '+(current.settings['template-version']?'模板 '+String(current.settings['template-version']).slice(0,8):'原始排版');$<HTMLInputElement>('title').value=current.title;$<HTMLTextAreaElement>('digest').value=current.digest||'';$<HTMLTextAreaElement>('sources').value=sourceNode()?.textContent?.trim()||'';document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-setting]').forEach(el=>{if(el instanceof HTMLInputElement&&el.type==='checkbox')el.checked=Boolean(current!.settings[el.id]);else el.value=String(current!.settings[el.id]??defaults[el.id]??'');});$<HTMLImageElement>('cover-preview').src=current.cover;$('image-tools').hidden=true;$('selection-label').textContent='全文';}
function applyStyle(){if(!current)return;const s=current.settings;styleRules(s).forEach(([selector,style])=>root.querySelectorAll<HTMLElement>(selector).forEach(el=>el.setAttribute('style',style)));const header=root.querySelector('[data-content-header]');String(s['block-order']).split(',').forEach(key=>{const block=header?.querySelector('[data-block="'+key+'"]');if(block)header!.append(block);});const caption=root.querySelector('[data-block="caption"]');if(caption){let p=caption.querySelector('p');if(!p){p=document.createElement('p');caption.replaceChildren(p);}p.textContent=String(s.caption);p.style.cssText=styleRules(s).find(([selector])=>selector==='[data-block="caption"] p')![1];}const sign=root.querySelector('[data-signature]');if(sign)sign.textContent=String(s['signature-text']);root.style.background=palette(s).bg;prepareEditing();}
function payload(){if(!current)throw new Error('请先选择文章');return {issueId:current.issueId,seriesId:current.seriesId,title:current.title,html:serialize(),cover:current.cover,settings:current.settings,digest:current.digest||''};}
async function refresh(){const b=await api<Bootstrap>('/api/library');items=b.snapshots;series=b.catalog.series;list();}
let savePromise:Promise<void>|null=null;
async function save():Promise<void>{if(savePromise){await savePromise;if(dirty)return save();return;}if(!current||!dirty)return;clearTimeout(saveTimer);const input=payload(),start=epoch;saving=true;updateState();savePromise=(async()=>{try{const result=await api<Item>('/api/save',input);if(current?.issueId===input.issueId){current.revision=result.revision;current.savedAt=result.savedAt;current.receipt=result.receipt;current.review=result.review;current.html=input.html;dirty=epoch!==start;}await refresh();}catch(e){dirty=true;throw e;}finally{saving=false;savePromise=null;updateState();}})();await savePromise;}
$('save').onclick=()=>void save().then(()=>notice('已保存到本机。')).catch(fail);
root.addEventListener('input',()=>{$<HTMLTextAreaElement>('sources').value=sourceNode()?.textContent?.trim()||'';const title=body()?.querySelector('h1')?.textContent?.trim();if(title&&current){current.title=title;$<HTMLInputElement>('title').value=title;$('article-heading').textContent=title;}changed();});
root.addEventListener('paste',ev=>{const e=ev as ClipboardEvent;e.preventDefault();document.execCommand('insertText',false,e.clipboardData?.getData('text/plain')||'');});
root.addEventListener('click',ev=>{const target=ev.target as HTMLElement;selectedBlock=target.closest('p,h1,h2,h3,blockquote,figure,li');if(target instanceof HTMLImageElement)selectImage(target);else{selectedImage?.classList.remove('selected-image');selectedImage=null;$('image-tools').hidden=true;$('selection-label').textContent=selectedBlock?.tagName==='H2'?'小标题':'正文';}});
document.addEventListener('selectionchange',()=>{const sel=window.getSelection();if(sel?.rangeCount&&body()?.contains(sel.anchorNode)){range=sel.getRangeAt(0).cloneRange();}});
function restoreRange(){if(range&&root.contains(range.commonAncestorContainer)){const sel=window.getSelection();sel?.removeAllRanges();sel?.addRange(range);}else body()?.focus();}
document.querySelectorAll<HTMLButtonElement>('[data-command],[data-block]').forEach(b=>{if(!b.closest('.format-toolbar'))return;b.onmousedown=e=>e.preventDefault();b.onclick=()=>{if(!current)return;if(b.dataset.command==='undo'){historyMove();return;}if(b.dataset.command==='redo'){historyMove(true);return;}restoreRange();if(b.dataset.block&&window.getSelection()?.anchorNode?.parentElement?.closest('h1')){notice('主标题请在右侧文章标题中编辑。');return;}if(b.dataset.block)document.execCommand('formatBlock',false,b.dataset.block);else if(b.dataset.command==='hilite')document.execCommand('foreColor',false,palette(settings()).accent);else document.execCommand(b.dataset.command!,false);markChanged();};});
$('link').onmousedown=e=>e.preventDefault();$('link').onclick=()=>{if(!current)return;dialog('添加链接','<label>链接地址<input id="link-url" type="url" placeholder="https://…"></label><div class="dialog-actions"><button id="link-ok" class="primary">插入链接</button></div>');$('link-ok').onclick=()=>{const href=$<HTMLInputElement>('link-url').value;try{const u=new URL(href);if(u.protocol!=='https:')throw new Error('请输入 HTTPS 链接');dlg.close();restoreRange();document.execCommand('createLink',false,u.href);markChanged();}catch(e){fail(e);}};};
$<HTMLInputElement>('title').oninput=()=>{if(!current)return;current.title=$<HTMLInputElement>('title').value;const h1=body()?.querySelector('h1');if(h1)h1.textContent=current.title;$('article-heading').textContent=current.title;changed();};
$<HTMLTextAreaElement>('digest').oninput=()=>{if(current){current.digest=$<HTMLTextAreaElement>('digest').value;changed();}};
document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-setting]').forEach(el=>el.oninput=()=>{if(!current)return;current.settings[el.id]=el instanceof HTMLInputElement&&el.type==='checkbox'?el.checked:el.value;applyStyle();changed();});
$('sources').oninput=()=>{if(!current)return;let node=sourceNode();if(!node){node=document.createElement('blockquote');node.dataset.sources='1';body()?.append(node);}node.textContent=$<HTMLTextAreaElement>('sources').value;changed();};
$('search').oninput=list;document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;document.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));list();});
$('series').onchange=async()=>{try{if(busy)throw new Error('请等待同步结束后切换');if(dirty)await save();activeSeries=$<HTMLSelectElement>('series').value;const next=latestItems().find(i=>i.seriesId===activeSeries);if(next)await openIssue(next.revision);else{current=null;root.replaceChildren();$('empty').hidden=false;$('article-heading').textContent='这个系列还没有文章';list();updateState();}}catch(e){renderSeries();fail(e);}};
document.querySelectorAll<HTMLButtonElement>('[data-width]').forEach(b=>b.onclick=()=>{root.style.width=b.dataset.width+'px';document.querySelectorAll('[data-width]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));});
function runChecks(){const errors:string[]=[],warnings:string[]=[];if(!current){$('checks').textContent='选择文章后开始检查';return {errors,warnings};}const text=body()?.textContent?.trim()||'',images=Array.from(root.querySelectorAll<HTMLImageElement>('img'));if(!body()?.querySelector('h1'))errors.push('正文标题缺失，请撤销或重新导入');if(!current.title.trim()||[...current.title].length>64)errors.push('标题需为 1–64 字');if(!current.cover.startsWith('data:image/'))errors.push('缺少完整封面');if(root.querySelectorAll('[data-content-header]').length!==1)errors.push('品牌开头必须且只能出现一次');if(!root.querySelector('[data-block="logo"] img'))errors.push('缺少品牌 Logo');if(images.length>30)errors.push('图片超过 30 张');if(/点击这里开始|待补充|TODO|\{\{.+?\}\}/.test(text))errors.push('正文仍有占位文字');if(text.length<80)warnings.push('正文较短，请检查是否完整');if(images.some(img=>!img.complete||!img.naturalWidth))warnings.push('图片尚未加载完成或无法显示');if(!sourceNode()?.textContent?.trim())warnings.push('尚未填写事实依据');const missing=Array.from(body()?.querySelectorAll('img')||[]).filter(img=>!img.alt.trim()).length;if(missing)warnings.push(missing+' 张正文图片缺少说明');if(!current.digest)warnings.push('未填写消息摘要');$('word-count').textContent=text.replace(/\s/g,'').length+' 字 · '+images.length+' 张图';$('checks').innerHTML=errors.map(x=>'<p class="check-bad">● '+esc(x)+'</p>').join('')+warnings.map(x=>'<p class="check-warn">○ '+esc(x)+'</p>').join('')+(!errors.length?'<p class="check-ok">✓ 本地结构检查通过</p>':'');return {errors,warnings};}
function showChecks(){const c=runChecks();dialog('全文检查',`<p>${c.errors.length?'请先处理以下问题':'结构检查通过，请确认内容事实与图片版权。'}</p>${$('checks').innerHTML}<p>本地检查不等于微信端视觉验收。</p>`);};
async function setReview(status:Review['status']){await save();if(!current||dirty)return;const review=await api<Review>('/api/review',{revision:current.revision,status});current.review=review;await refresh();updateState();}
$('review').onchange=()=>void setReview($<HTMLSelectElement>('review').value as Review['status']).catch(fail);
function selectImage(img:HTMLImageElement){selectedImage?.classList.remove('selected-image');selectedImage=img;img.classList.add('selected-image');$('image-tools').hidden=false;document.querySelector('.inspector')!.scrollTo({top:0,behavior:'smooth'});$('selection-label').textContent=img.closest('[data-block]')?'品牌图片':'正文图片';$<HTMLImageElement>('image-preview').src=img.src;$<HTMLInputElement>('image-alt').value=img.alt;$<HTMLInputElement>('image-caption').value=img.closest('figure')?.querySelector('figcaption')?.textContent||'';$<HTMLInputElement>('image-source').value=img.dataset.source||'';const width=parseInt(img.style.width)||100;$<HTMLInputElement>('image-width').value=String(width);$('image-width-value').textContent=width+'%';$<HTMLSelectElement>('image-align').value=img.style.marginLeft==='0px'?'left':img.style.marginRight==='0px'?'right':'center';for(const id of ['image-remove','image-up','image-down','image-caption','image-source','image-width','image-align'])($<HTMLButtonElement>(id)).disabled=!!img.closest('[data-block]');}
function imageBlock(img:HTMLImageElement):HTMLElement{return img.closest('figure')||((img.parentElement?.tagName==='P'&&img.parentElement.textContent?.trim()==='')?img.parentElement:img);}
$('image-align').onchange=()=>{if(selectedImage){const align=$<HTMLSelectElement>('image-align').value;selectedImage.style.marginLeft=align==='left'?'0':'auto';selectedImage.style.marginRight=align==='right'?'0':'auto';changed();}};
$('image-alt').oninput=()=>{if(selectedImage){selectedImage.alt=$<HTMLInputElement>('image-alt').value;changed();}};
$('image-width').oninput=()=>{if(selectedImage){const value=$<HTMLInputElement>('image-width').value;selectedImage.style.width=value+'%';selectedImage.style.display='block';selectedImage.style.margin='24px auto';$('image-width-value').textContent=value+'%';changed();}};
$('image-caption').oninput=()=>{if(!selectedImage||selectedImage.closest('[data-block]'))return;let figure=selectedImage.closest('figure');if(!figure){figure=document.createElement('figure');const block=imageBlock(selectedImage);block.replaceWith(figure);figure.append(selectedImage);}let caption=figure.querySelector('figcaption');if(!caption){caption=document.createElement('figcaption');figure.append(caption);}caption.textContent=$<HTMLInputElement>('image-caption').value;caption.style.cssText=styleRules(settings()).find(([s])=>s==='article figcaption')![1];changed();};
$('image-source').onchange=()=>{if(!selectedImage)return;const v=$<HTMLInputElement>('image-source').value.trim();if(v&&!/^https:\/\//.test(v)){notice('图片来源请填写 HTTPS 链接',true);return;}selectedImage.dataset.source=v;changed();};
for(const direction of ['up','down'])$('image-'+direction).onclick=()=>{if(!selectedImage||selectedImage.closest('[data-block]'))return;const block=imageBlock(selectedImage),neighbor=direction==='up'?block.previousElementSibling:block.nextElementSibling;if(neighbor&&neighbor.tagName!=='H1'){if(direction==='up')neighbor.before(block);else neighbor.after(block);markChanged();}};
$('image-remove').onclick=()=>{if(!selectedImage||selectedImage.closest('[data-block]'))return;imageBlock(selectedImage).remove();selectedImage=null;$('image-tools').hidden=true;markChanged();};
async function imageData(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw new Error('请选择 20MB 以内的 PNG、JPG 或 WebP');const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas'),scale=Math.min(1,1600/bitmap.width);canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d')!;ctx.fillStyle=palette(settings()).bg==='transparent'?'#ffffff':palette(settings()).bg;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.86);}finally{bitmap.close();}}
let fileAction:(src:string)=>void=()=>{};
function filePick(action:(src:string)=>void){fileAction=action;$<HTMLInputElement>('file').click();}
$('file').onchange=async()=>{const input=$<HTMLInputElement>('file');try{if(input.files?.[0])fileAction(await imageData(input.files[0]));}catch(e){fail(e);}finally{input.value='';}};
function replaceImage(img:HTMLImageElement,src:string){img.src=src;if(img.closest('[data-block="cover"]')&&current){current.cover=src;$<HTMLImageElement>('cover-preview').src=src;}selectImage(img);markChanged();}
$('image-replace').onclick=()=>{const img=selectedImage;if(img)filePick(src=>replaceImage(img,src));};
$('cover-replace').onclick=()=>{const img=root.querySelector<HTMLImageElement>('[data-block="cover"] img');if(img)filePick(src=>replaceImage(img,src));};
$('logo-replace').onclick=()=>{const img=root.querySelector<HTMLImageElement>('[data-block="logo"] img');if(img)filePick(src=>replaceImage(img,src));};
$('insert-image').onclick=()=>{if(!current)return;const after=selectedImage?imageBlock(selectedImage):selectedBlock;filePick(src=>{const f=document.createElement('figure'),img=document.createElement('img');img.src=src;img.alt='';img.style.cssText='display:block;width:100%;height:auto;margin:24px auto';f.append(img);if(after&&body()?.contains(after))after.after(f);else body()?.append(f);selectImage(img);markChanged();});};
$('crop').onclick=async()=>{try{const img=selectedImage;if(!img)return;if(!img.src.startsWith('data:'))throw new Error('请先替换为本地图片后裁切，避免微信图片跨域限制');const source=new Image();source.src=img.src;await source.decode();const ratio=Number($<HTMLSelectElement>('crop-ratio').value),w=source.naturalWidth,h=source.naturalHeight,sw=Math.min(w,h*ratio),sh=sw/ratio;const c=document.createElement('canvas');c.width=Math.round(sw);c.height=Math.round(sh);c.getContext('2d')!.drawImage(source,(w-sw)/2,(h-sh)/2,sw,sh,0,0,c.width,c.height);replaceImage(img,c.toDataURL('image/jpeg',.9));}catch(e){fail(e);}};
async function copy(){await save();const html=serialize();if(navigator.clipboard&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([root.textContent||''],{type:'text/plain'})})]);else throw new Error('当前浏览器不支持富文本复制，请导出备份或同步草稿');notice('完整图文已复制，可粘贴到公众号编辑器。');}
$('copy').onclick=()=>void copy().catch(fail);
$('export').onclick=async()=>{try{await save();if(!current)return;const a=document.createElement('a');a.href='/api/export?revision='+current.revision;a.download='article-backup.json';a.click();}catch(e){fail(e);}};
$('import').onclick=()=>$<HTMLInputElement>('import-file').click();$('import-file').onchange=async()=>{const input=$<HTMLInputElement>('import-file');try{if(!input.files?.[0])return;if(input.files[0].size>20*1024*1024)throw new Error('备份超过 20MB');if(dirty)await save();const value=JSON.parse(await input.files[0].text());const result=await api<Item>('/api/save',value);await refresh();if(!series.some(s=>s.id===value.seriesId)){series.push({id:value.seriesId,name:'导入系列',layout:'独立模板'});await api('/api/catalog',{series});}await openIssue(result.revision);notice('已导入文章，原有版本已保留。');}catch(e){fail(e);}finally{input.value='';}};
$('history').onclick=()=>{if(!current)return;const rows=items.filter(i=>i.issueId===current!.issueId&&i.seriesId===current!.seriesId);dialog('文章历史版本',rows.map(i=>`<button class="history-item" data-history="${i.revision}">${date(i.savedAt)} · ${i.revision.slice(0,8)}<br>${i.receipt?.status==='verified'?'已同步草稿':'本地版本'} · ${i.imageCount} 张图片</button>`).join('')||'<p>尚无历史版本。</p>');document.querySelectorAll<HTMLButtonElement>('[data-history]').forEach(b=>b.onclick=()=>{dlg.close();void openIssue(b.dataset.history!).catch(fail);});};
async function getTemplate(){return api<Template|null>('/api/template?seriesId='+activeSeries);}
async function applyTemplate(){if(!current)return;const t=await getTemplate();const s=t?.settings||series.find(s=>s.id===activeSeries)?.settings||defaults;current.settings={...current.settings,...templateSettings(s),'template-version':t?.revision||'legacy'};const logo=root.querySelector<HTMLImageElement>('[data-block="logo"] img');if(t?.logo&&logo)logo.src=t.logo;applyStyle();populate();markChanged();notice('系列模板已应用到本文。历史版本保持原样。');}
$('apply-template').onclick=()=>void applyTemplate().catch(fail);
$('template').onclick=async()=>{try{if(busy)return;const t=await getTemplate();const entry=series.find(s=>s.id===activeSeries);let logo=t?.logo||(current?.seriesId===activeSeries?root.querySelector<HTMLImageElement>('[data-block="logo"] img')?.src:'')||'';await editTemplate({seriesId:activeSeries,name:entry?.name||'系列',existing:t,settings:entry?.settings||defaults,logo,save:async value=>{const saved=await api<Template>('/api/template',value);$('template-series-name').textContent='最新模板 · '+date(saved.savedAt);return saved;}});}catch(e){fail(e);}};
$('add-series').onclick=()=>{if(busy)return;dialog('添加系列','<label>系列名称<input id="series-name" maxlength="80" placeholder="例如：AI 工具实测"></label><div class="dialog-actions"><button id="series-create" class="primary">创建系列</button></div>');$('series-create').onclick=async()=>{try{const name=$<HTMLInputElement>('series-name').value.trim();if(!name)throw new Error('请填写系列名称');if(dirty)await save();const entry={id:'series-'+crypto.randomUUID(),name,createdAt:new Date().toISOString(),layout:'独立排版模板',settings:templateSettings(settings())};series.push(entry);await api('/api/catalog',{series});activeSeries=entry.id;current=null;root.replaceChildren();$('empty').hidden=false;renderSeries();list();updateState();dlg.close();}catch(e){fail(e);}};};
$('new').onclick=async()=>{try{if(busy)throw new Error('请等待同步结束后新建');if(dirty)await save();dialog('新建一期','<label>文章标题<input id="new-title" maxlength="64"></label><label>本期封面<input id="new-cover" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="dialog-actions"><button id="new-create" class="primary">创建并编辑</button></div>');$('new-create').onclick=async()=>{try{const title=$<HTMLInputElement>('new-title').value.trim(),file=$<HTMLInputElement>('new-cover').files?.[0];if(!title||!file)throw new Error('请填写标题并选择本期封面');const t=await getTemplate();let logo=t?.logo||root.querySelector<HTMLImageElement>('[data-block="logo"] img')?.src;if(!logo){const prior=items[0];if(prior){const snap=await api<Snapshot>('/api/snapshot?revision='+prior.revision);logo=new DOMParser().parseFromString(snap.html,'text/html').querySelector<HTMLImageElement>('[data-block="logo"] img')?.src;}}if(!logo)throw new Error('请先导入带品牌 Logo 的完整文章');const cover=await imageData(file);current={issueId:'issue-'+crypto.randomUUID(),seriesId:activeSeries,title,digest:'',revision:'',savedAt:new Date().toISOString(),imageCount:2,cover,settings:{...defaults,...templateSettings(t?.settings||series.find(s=>s.id===activeSeries)?.settings||defaults),'template-version':t?.revision||'legacy'},html:''};root.innerHTML='<section data-content-header="1"><section data-block="logo"><img src="'+logo+'" alt="Content Desk"></section><section data-block="cover"><img src="'+cover+'" alt="本期封面"></section><section data-block="caption"><p></p></section></section><article><section><h1>'+esc(title)+'</h1><p>点击这里开始撰写正文。</p></section></article><section data-signature="1"></section>';applyStyle();populate();undoStack=[];redoStack=[];checkpoint=stateString();changed();await save();dlg.close();list();}catch(e){fail(e);}};}catch(e){fail(e);}};
async function connection(){const b=await api<{configured:boolean;configurationError?:string}>('/api/config-status');configured=b.configured;$('connection').textContent=b.configured?'公众号配置可读取 · 同步时验证接口权限':'同步暂不可用：'+(b.configurationError||'未配置公众号');updateState();return b;}
$('reconnect').onclick=()=>void connection().then(b=>notice(b.configured?'公众号配置可读取':$('connection').textContent||'连接检查失败',!b.configured)).catch(fail);
async function sync(){if(!current||busy||checkingConnection)return;checkingConnection=true;updateState();try{const status=await connection();if(!status.configured)throw new Error('同步暂不可用：'+(status.configurationError||'未配置公众号'));}finally{checkingConnection=false;updateState();}await save();const checks=runChecks();if(checks.errors.length){showChecks();return;}const prior=items.find(i=>i.issueId===current!.issueId&&i.seriesId===current!.seriesId&&i.receipt?.status==='verified');dialog('检查并同步到微信草稿箱',`<p>《${esc(current.title)}》</p><p>将同步已保存版本 ${current.revision.slice(0,8)}。${prior?.revision===current.revision?'当前版本已有成功回执，将保留现有草稿。':prior?'默认更新同一篇草稿。':'将新建一篇草稿。'}不会群发或发布。</p>${checks.warnings.length?'<p>'+checks.warnings.map(esc).join('<br>')+'</p>':''}<label class="check-label"><input id="review-confirm" type="checkbox">我已检查本版本的文字、图片和来源</label>${prior&&prior.revision!==current.revision?'<label class="check-label"><input id="force-new" type="checkbox">另存为新草稿（保留旧草稿）</label>':''}<div class="dialog-actions"><button id="sync-confirm" class="primary" disabled>确认同步</button></div>`);$('review-confirm').onchange=()=>{$<HTMLButtonElement>('sync-confirm').disabled=!$<HTMLInputElement>('review-confirm').checked;};$('sync-confirm').onclick=async()=>{const forceNew=$<HTMLInputElement>('force-new')?.checked||false;dlg.close();busy=true;updateState();root.inert=true;document.querySelector<HTMLElement>('.inspector')!.inert=true;try{await setReview('reviewed');const id=current!.revision;const result=await api<Receipt>('/api/push-draft',{revision:id,forceNew});if(result.status==='verified'){notice('此版本已同步，未重复提交。');}else{let done=false;for(let i=0;i<180;i++){const r=await api<Receipt|null>('/api/receipt?revision='+id);if(r){current!.receipt=r;updateState();$('save-state').textContent='同步中 · '+r.stage;if(r.status==='verified'){done=true;notice('微信草稿已同步并回读核对。');break;}if(r.error||['failed','uncertain'].includes(r.status))throw new Error(r.error||'同步结果未确认，请核对草稿箱');}await new Promise(resolve=>setTimeout(resolve,1000));}if(!done)throw new Error('同步仍在进行，请稍后检查回执，不要重复提交');}await refresh();}catch(e){fail(e);}finally{busy=false;root.inert=false;document.querySelector<HTMLElement>('.inspector')!.inert=false;updateState();}};}
$('sync').onclick=()=>void sync().catch(fail);
$('logs').onclick=async()=>{try{const data=await api<{entries:Array<{time:string;task:string;badge:string;detail:string}>}>('/api/automation-log');dialog('自动化运行记录',data.entries.map(e=>`<details class="log-item"><summary>${esc(e.time)} · ${esc(e.task)}</summary><pre>${esc(e.detail)}</pre></details>`).join('')||'<p>尚无运行记录。</p>');}catch(e){fail(e);}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void save().catch(fail);}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&root.contains(document.activeElement)){e.preventDefault();historyMove(e.shiftKey);}});
async function boot(){try{const b=await api<Bootstrap>('/api/bootstrap');token=b.token;items=b.snapshots;series=b.catalog.series;online=true;configured=b.configured;if(!series.length){series=[{id:'my-first-series',name:'我的第一个系列',layout:'暗夜品牌排版',settings:{...defaults}}];await api('/api/catalog',{series});}for(const item of latestItems()){const key='wb-status:'+item.seriesId+':'+item.issueId,mark='desk-migrated:'+key;if(!localStorage.getItem(mark)){const old=localStorage.getItem(key);if(old&&!item.review){item.review=await api<Review>('/api/review',{revision:item.revision,status:old==='已发布'?'published':old==='已同步'?'reviewed':'pending'});}localStorage.setItem(mark,'1');}}const latest=latestItems(),requested=new URLSearchParams(location.search).get('revision'),next=latest.find(i=>i.revision===requested)||latest.find(i=>!i.review&&i.receipt?.status!=='verified')||latest[0];activeSeries=next?.seriesId||series[0].id;renderSeries();if(next)await openIssue(next.revision);else{list();updateState();} $('connection').textContent=configured?'公众号配置可读取 · 同步时验证接口权限':'同步暂不可用：'+(b.configurationError||'未配置公众号');setInterval(()=>void poll().catch(()=>{}),30000);}catch(e){fail(e);$('save-state').textContent='连接失败，请刷新重试';}}
async function poll(){const before=new Set(latestItems().map(i=>i.revision));await refresh();const fresh=latestItems().find(i=>!before.has(i.revision)&&i.revision!==current?.revision&&!i.review&&i.receipt?.status!=='verified');if(fresh){notice('有新文章待检查：'+fresh.title);const b=document.createElement('button');b.textContent='去检查';b.onclick=()=>void openIssue(fresh.revision).then(()=>notice('')).catch(fail);$('notice').append(b);}}
void boot();
