import {proUI} from './pro-ui';
import {parseArtifact,moduleKinds,type ContentArtifact,type ContentModule,type TemplateSlot,type ModuleKind} from './content-contract';
import type {SavedArtifact} from './artifact-store';
import type {Job} from './agent-runner';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const labels:Record<ModuleKind,string>={heading:'小标题',paragraph:'正文',quote:'引用',list:'列表',image:'图片',sources:'事实依据',signature:'署名'};
const names={module:'模块',template:'内容模板',article:'文章'};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const copy=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
let token='',saved:SavedArtifact[]=[],filter='all',selected='',draft:ContentArtifact,jobId='',activeJob='',dirty=false;
let installed:Array<{provider:string;installed:boolean;version:string}>=[];
function message(text:string,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function failure(e:unknown){message(e instanceof Error?e.message:String(e),true);}
async function api<T>(url:string,value?:unknown):Promise<T>{const r=await fetch(url,{method:value===undefined?'GET':'POST',headers:value===undefined?{}:{'Content-Type':'application/json','X-Workbench-Token':token},body:value===undefined?undefined:JSON.stringify(value)});const result=await r.json();if(!r.ok)throw new Error(result.error||'请求失败');return result;}
function empty(type:ContentArtifact['type']):ContentArtifact{return {schemaVersion:1,type,title:type==='template'?'我的内容模板':type==='module'?'我的模块':'我的新文章',description:'',audience:'',voice:'',modules:type==='template'?[]:[module('paragraph')],slots:type==='template'?[slot('paragraph')]:[]};}
function module(kind:ModuleKind):ContentModule{return {id:'m-'+crypto.randomUUID(),kind,text:kind==='image'||kind==='list'?'':'在这里写下你的内容。',items:kind==='list'?['第一条内容']:[],assetId:'',alt:''};}
function slot(kind:ModuleKind):TemplateSlot{return {id:'s-'+crypto.randomUUID(),kind,label:labels[kind],instruction:'说明这个模块应该生成什么，以及需要遵守的要求。',required:true};}
function changed(){dirty=true;jobId='';selected='';$('save-hint').textContent='有修改 · 点击保存为独立版本';preview();}
function switchDraft(value:ContentArtifact,id='',fromJob=''){if(dirty&&!confirm('当前修改尚未保存，确定切换吗？'))return false;draft=copy(value);selected=id;jobId=fromJob;dirty=!!fromJob;$<HTMLSelectElement>('task-type').value=draft.type;fields();library();return true;}
function fields(){for(const [id,key] of [['artifact-title','title'],['description','description'],['audience','audience'],['voice','voice']] as const)$<HTMLInputElement>(id).value=draft[key];$('artifact-kind').textContent=names[draft.type];$('block-heading').textContent=draft.type==='template'?'内容结构':'内容模块';$('add-block').hidden=draft.type==='module';$('reuse-label').hidden=draft.type==='module';$('save-hint').textContent=dirty?'等待你检查并保存':'保存为独立版本，已有内容保留';blocks();preview();}
function library(){const rows=saved.filter(s=>filter==='all'||s.artifact.type===filter);$('count').textContent=String(saved.length);$('library').innerHTML=rows.length?rows.map(s=>`<button class="library-item ${selected===s.id?'selected':''}" data-artifact="${s.id}"><span class="item-kind">${names[s.artifact.type]}</span><b>${esc(s.artifact.title)}</b><small>${s.artifact.type==='template'?s.artifact.slots.length+' 个结构模块':s.artifact.modules.length+' 个内容模块'}</small></button>`).join(''):'<p class="empty">还没有保存的内容。<br>从空白开始，或交给 Agent。</p>';$('library').querySelectorAll<HTMLButtonElement>('[data-artifact]').forEach(b=>b.onclick=()=>{const item=saved.find(s=>s.id===b.dataset.artifact);if(item)switchDraft(item.artifact,item.id);});$('reuse').innerHTML='<option value="">选择一个模块加入当前内容</option>'+saved.filter(s=>s.artifact.type==='module').map(s=>`<option value="${s.id}">${esc(s.artifact.title)}</option>`).join('');const prior=$<HTMLSelectElement>('template-choice').value;$('template-choice').innerHTML='<option value="">不指定模板</option>'+saved.filter(s=>s.artifact.type==='template').map(s=>`<option value="${s.id}">${esc(s.artifact.title)}</option>`).join('');$<HTMLSelectElement>('template-choice').value=prior;}
function blocks(){const list=draft.type==='template'?draft.slots:draft.modules;$('blocks').innerHTML=list.map((b,i)=>`<section class="block" data-index="${i}"><div class="block-head"><select data-field="kind" aria-label="模块类型">${moduleKinds.map(k=>`<option value="${k}" ${b.kind===k?'selected':''}>${labels[k]}</option>`).join('')}</select><button data-move="-1" aria-label="上移模块" ${i===0?'disabled':''}>↑</button><button data-move="1" aria-label="下移模块" ${i===list.length-1?'disabled':''}>↓</button><button data-remove aria-label="移除模块" ${list.length===1?'disabled':''}>×</button></div>${draft.type==='template'?`<label>模块名称<input data-field="label" value="${esc((b as TemplateSlot).label)}"></label><label>写作要求<textarea data-field="instruction" rows="3">${esc((b as TemplateSlot).instruction)}</textarea></label><label class="required"><input type="checkbox" data-field="required" ${(b as TemplateSlot).required?'checked':''}>必须包含</label>`:`<label>${b.kind==='list'?'列表内容（每行一条）':'内容'}<textarea data-field="${b.kind==='list'?'items':'text'}" rows="4">${esc(b.kind==='list'?(b as ContentModule).items.join('\n'):(b as ContentModule).text)}</textarea></label>${b.kind==='image'?`<label>素材 ID<input data-field="assetId" value="${esc((b as ContentModule).assetId)}"></label><label>图片说明<input data-field="alt" value="${esc((b as ContentModule).alt)}"></label>`:''}`}</section>`).join('');
 $('blocks').querySelectorAll<HTMLElement>('.block').forEach(section=>{const i=Number(section.dataset.index);section.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-field]').forEach(el=>el.oninput=()=>{const field=el.dataset.field!;const item=list[i] as unknown as Record<string,unknown>;item[field]=el instanceof HTMLInputElement&&el.type==='checkbox'?el.checked:field==='items'?el.value.split('\n').filter(Boolean):el.value;changed();if(field==='kind')blocks();});section.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(b=>b.onclick=()=>{const j=i+Number(b.dataset.move);if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];changed();blocks();});section.querySelector<HTMLButtonElement>('[data-remove]')!.onclick=()=>{list.splice(i,1);changed();blocks();};});
}
function preview(){const contents=draft.type==='template'?draft.slots.map((s,i)=>`<section class="slot-preview"><span>${String(i+1).padStart(2,'0')} / ${labels[s.kind]}${s.required?' · 必填':''}</span><h3>${esc(s.label)}</h3><p>${esc(s.instruction)}</p></section>`).join(''):draft.modules.map(m=>{const text=esc(m.text).replace(/\n/g,'<br>');if(m.kind==='heading')return `<h3>${text}</h3>`;if(['quote','sources'].includes(m.kind))return `<blockquote>${text}</blockquote>`;if(m.kind==='list')return `<ul>${m.items.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`;if(m.kind==='image')return `<blockquote>图片素材：${esc(m.assetId||'未指定')}<br>${esc(m.alt)}</blockquote>`;return `<p>${text}</p>`;}).join('');$('preview').innerHTML=`<article class="paper"><span class="paper-brand">CONTENT DESK / ${draft.type==='template'?'BLUEPRINT':'DRAFT'}</span><h2>${esc(draft.title)}</h2>${draft.description?`<p class="paper-description">${esc(draft.description)}</p>`:''}${contents}</article>`;$('editor-actions').hidden=draft.type!=='article';}
for(const [id,key] of [['artifact-title','title'],['description','description'],['audience','audience'],['voice','voice']] as const)$<HTMLInputElement>(id).oninput=()=>{draft[key]=$<HTMLInputElement>(id).value;changed();};
$('add-block').onclick=()=>{if(draft.type==='template')draft.slots.push(slot('paragraph'));else draft.modules.push(module('paragraph'));changed();blocks();};
$('reuse').onchange=()=>{const entry=saved.find(s=>s.id===$<HTMLSelectElement>('reuse').value);if(!entry||entry.artifact.type!=='module')return;const content=copy(entry.artifact.modules[0]);if(draft.type==='template')draft.slots.push({...slot(content.kind),label:entry.artifact.title,instruction:entry.artifact.description||content.text});else if(draft.type==='article')draft.modules.push({...content,id:'m-'+crypto.randomUUID()});changed();blocks();$<HTMLSelectElement>('reuse').value='';};
$('blank').onclick=()=>switchDraft(empty($<HTMLSelectElement>('task-type').value as ContentArtifact['type']));
document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('selected',el===b));library();});
async function refresh(){const state=await api<{artifacts:SavedArtifact[];jobs:Job[];series:Array<{id:string;name:string}>}>('/api/studio/state');saved=state.artifacts;library();$('target-series').innerHTML=state.series.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');return state;}
$('save').onclick=async()=>{try{const value=parseArtifact(draft);const result=await api<SavedArtifact>('/api/studio/save',{artifact:value,jobId:jobId||undefined});dirty=false;selected=result.id;jobId='';await refresh();$('save-hint').textContent='已保存 · '+result.id.slice(0,8);message('已保存到本地素材库');}catch(e){failure(e);}};
$('export').onclick=()=>{try{const data=parseArtifact(draft);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='content-desk-'+data.type+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){failure(e);}};
$('import').onclick=()=>$<HTMLInputElement>('import-file').click();$<HTMLInputElement>('import-file').onchange=async()=>{try{const file=$<HTMLInputElement>('import-file').files?.[0];if(!file)return;if(file.size>10*1024*1024)throw new Error('文件超过 10MB');const input=JSON.parse(await file.text());if(input?.format==='content-desk-bundle'){if(!Array.isArray(input.artifacts))throw new Error('素材库备份格式无效');if(!confirm('将导入 '+input.artifacts.length+' 项素材；已有版本会保留，重复项会跳过。继续吗？'))return;const result=await api<{imported:number;existing:number}>('/api/studio/import-bundle',{bundle:input});await refresh();message('素材库已恢复：新增 '+result.imported+' 项，跳过重复 '+result.existing+' 项');}else{const value=parseArtifact(input);if(switchDraft(value)){dirty=true;message('已导入预览，检查后保存到素材库');}}}catch(e){failure(e);}finally{$<HTMLInputElement>('import-file').value='';}};
function agentStatus(){const found=installed.find(a=>a.provider===$<HTMLSelectElement>('provider').value);$('agent-status').textContent=found?.installed?found.version+' · 使用前请在终端登录':'未检测到 CLI，请先安装并在终端登录';$<HTMLButtonElement>('generate').disabled=!!activeJob||!found?.installed;}
async function detect(){try{installed=(await api<{agents:typeof installed}>('/api/studio/agents')).agents;agentStatus();}catch(e){failure(e);}}
$('detect').onclick=()=>void detect();$('provider').onchange=agentStatus;
function showJob(job:Job){$('job-status').hidden=false;$('job-status').textContent=job.status==='running'?'正在生成 · '+job.provider+' · 完成后会显示预览，尚未写入内容库':job.status==='ready'?'生成完成，请检查预览并保存。':job.status==='cancelled'?'任务已停止。':job.error||'任务已完成';$('cancel').hidden=job.status!=='running';}
async function pollJob(){if(!activeJob)return;try{const job=await api<Job>('/api/studio/job?id='+activeJob);showJob(job);if(job.status!=='running'){activeJob='';agentStatus();if(job.status==='ready'&&job.result){if(switchDraft(job.result,'',job.id))message('生成完成，等待你检查');}else if(job.status==='failed')message(job.error||'生成失败',true);return;}}catch(e){failure(e);}setTimeout(()=>void pollJob(),1500);}
$('generate').onclick=async()=>{try{if(dirty&&!confirm('当前修改尚未保存，生成结果将替换预览，是否继续？'))return;const job=await api<Job>('/api/studio/generate',{provider:$<HTMLSelectElement>('provider').value,type:$<HTMLSelectElement>('task-type').value,prompt:$<HTMLTextAreaElement>('prompt').value,templateId:$<HTMLSelectElement>('template-choice').value||undefined});dirty=false;activeJob=job.id;showJob(job);agentStatus();void pollJob();}catch(e){failure(e);}};
$('cancel').onclick=async()=>{try{if(activeJob){const job=await api<Job>('/api/studio/cancel',{id:activeJob});activeJob='';showJob(job);agentStatus();}}catch(e){failure(e);}};
$('to-editor').onclick=async()=>{try{const result=await api<{url:string}>('/api/studio/to-editor',{artifact:parseArtifact(draft),seriesId:$<HTMLSelectElement>('target-series').value});dirty=false;location.href=result.url;}catch(e){failure(e);}};
const pro=proUI({api,message,context:()=>({provider:$<HTMLSelectElement>('provider').value,type:$<HTMLSelectElement>('task-type').value,templateId:$<HTMLSelectElement>('template-choice').value||undefined}),preview:job=>!!job.result&&switchDraft(job.result,'',job.status==='ready'?job.id:'')});$('close-dialog').onclick=()=>$<HTMLDialogElement>('dialog').close();
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function boot(){try{token=(await api<{token:string}>('/api/bootstrap')).token;const state=await refresh();draft=copy(saved.find(s=>s.artifact.type==='template')?.artifact||empty('template'));selected=saved.find(s=>s.artifact===draft)?.id||'';fields();library();message('本地工作区已就绪');void pro.refresh().catch(failure);void detect();const job=state.jobs.find(j=>j.status==='running');if(job){activeJob=job.id;void pollJob();}else{const ready=state.jobs.find(j=>j.status==='ready'&&j.result);if(ready?.result){switchDraft(ready.result,'',ready.id);showJob(ready);}}}catch(e){failure(e);}}
void boot();
