export const studioShell=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Content Desk · 创作室</title><style>/*STYLE*/</style></head><body>
<header class="top"><a class="wordmark" href="/studio"><span class="mark">C<span>↗</span></span>Content Desk <small>COMMUNITY</small></a><nav><a class="active" href="/studio">创作室</a><a href="/editor">文章工作台 ↗</a><button id="edition">版本权益</button></nav><span id="status" role="status">正在打开本地工作区…</span></header>
<div class="intro"><div><span class="eyebrow">YOUR IDEAS. YOUR SYSTEM.</span><h1>把想法，做成你的内容系统<span>。</span></h1></div><p>自己搭模块，让 Agent 做重复的事。<br>从一个模板，到每一期值得分享的内容。</p></div>
<main class="studio"><aside class="library"><div class="section-heading"><h2>我的素材库</h2><span id="count">0</span></div><div class="tabs" aria-label="素材筛选"><button data-filter="all" class="selected">全部</button><button data-filter="template">模板</button><button data-filter="module">模块</button><button data-filter="article">文章</button></div><div id="library"></div><div class="library-footer"><button id="blank">＋ 从空白开始</button><button id="import">导入 JSON</button><input id="import-file" type="file" accept="application/json" hidden></div><div class="local-note"><span class="dot"></span>内容保存在这台电脑<br><span>模型使用你自己的 CLI 账号</span></div></aside>
<section class="composer"><div class="section-heading"><h2>01 <span>生成与 DIY</span></h2><span class="label">LOCAL AGENT</span></div><section class="generation"><div class="two-fields"><label>生成什么<select id="task-type"><option value="template">内容模板</option><option value="module">单个模块</option><option value="article">完整文章</option></select></label><label>使用 Agent<select id="provider"><option value="codex">Codex CLI</option><option value="claude">Claude Code</option></select></label></div><div class="agent-line"><span id="agent-status">检测本地 CLI…</span><button id="detect">重新检测</button></div><label>沿用内容模板<select id="template-choice"><option value="">不指定模板</option></select></label><label>这次想做什么？<textarea id="prompt" rows="4" placeholder="例如：做一个独立开发者产品周报模板。先讲本周进展，再讲一次踩坑，最后给读者可复用的方法。"></textarea></label><div class="generate-actions"><small>仅发送你填写的要求与选中的模板</small><button id="cancel" hidden>停止</button><button id="generate" class="primary">交给 Agent ↗</button></div><div id="job-status" hidden role="status"></div></section>
<section class="design"><div class="section-heading"><h2>手动调整</h2><span id="artifact-kind">内容模板</span></div><label>名称<input id="artifact-title" maxlength="64"></label><label>介绍<textarea id="description" rows="2"></textarea></label><div class="two-fields"><label>写给谁<input id="audience"></label><label>表达风格<input id="voice"></label></div><div class="section-heading module-heading"><h3 id="block-heading">内容结构</h3><button id="add-block">＋ 添加模块</button></div><label id="reuse-label">复用已保存模块<select id="reuse"><option value="">选择一个模块加入当前内容</option></select></label><div id="blocks"></div></section></section>
<section class="preview-pane"><div class="section-heading"><h2>02 <span>实时预览</span></h2><span class="label">YOUR CANVAS</span></div><div id="preview"></div><footer class="preview-actions"><div><span id="save-hint">保存为独立版本，已有内容保留</span><div class="preview-buttons"><button id="export">导出 JSON</button><button id="save" class="primary">保存到素材库</button></div></div><div id="editor-actions" hidden><select id="target-series" aria-label="目标系列"></select><button id="to-editor">进入文章编辑器 ↗</button></div></footer></section></main>
<dialog id="dialog"><div class="dialog-heading"><h2>选择适合你的创作方式</h2><button id="close-dialog" aria-label="关闭">×</button></div><div class="editions"><section><span class="eyebrow">COMMUNITY</span><h2>免费，自由地创作。</h2><p>本地文章与系列不限数量；DIY 模块和模板；Codex / Claude Code 单任务生成；文章编辑、版本、备份和公众号草稿同步。</p><strong>永久免费 · 开源核心</strong></section><section><span class="eyebrow">PRO · 规划中</span><h2>把效率再往前推一步。</h2><p>批量生产、定时工作流、多品牌、多公众号、高级模板包、版本对比与优先支持。</p><strong>买断方案设计中，尚未开放购买</strong></section></div><p class="muted">AI 模型费用由你自己的 CLI 账号承担。Pro 未上线功能不会在当前版本中伪装可用。</p></dialog>
<script type="module">/*SCRIPT*/</script></body></html>`;
